server:
  port: 8080
  servlet:
    context-path: /sale_ticket

spring:
  application:
    name: exam1
  datasource:
    url: jdbc:mysql://localhost:3306/sale_ticket?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # database-platform: org.hibernate.dialect.MySQLDialect # Hibernate 6+ often auto-detects this
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "ef03bad871c220f440e6975a1427d0aa6b3b1bfbcd9341016505cdda3dbee331"
  valid-duration: 3600
  refresh-duration: 36000
logging:
  level:
    me.paulschwarz: DEBUG